export const SETTINGS_GROUPS = [
  {
    title: "Business Profile",
    description: "Business identity and document display information.",
    items: [
      "Business name",
      "Business logo",
      "Main address",
      "Contact number",
      "Email address",
      "Facebook page",
      "Receipt footer note",
      "Quotation footer note",
      "Warranty note",
    ],
  },
  {
    title: "Branch Settings",
    description: "Per-branch profile and operational details.",
    items: [
      "Branch name",
      "Branch code",
      "Branch address",
      "Branch contact number",
      "Branch status",
      "Assigned branch owner/admin",
      "Branch receipt header",
      "Branch quotation/DR header",
    ],
  },
  {
    title: "Payment Methods",
    description: "Enable payment types and required payment reference fields.",
    items: [
      "Cash enabled",
      "GCash enabled",
      "Bank transfer enabled",
      "Card / payment terminal enabled",
      "Cheque enabled",
      "Credit / installment enabled",
      "Mixed payment enabled",
      "Reference number required",
      "Approval code required for card terminal",
      "Cheque number required",
      "Bank name required",
      "Remarks requirement",
    ],
  },
  {
    title: "Installment / Interest Rates",
    description: "Owner/Admin controlled rates and terms. Sales Agents only select terms.",
    items: [
      "Straight payment basis",
      "3 months rate / percentage",
      "6 months rate / percentage",
      "9 months rate / percentage",
      "12 months rate / percentage",
      "18 months rate / percentage",
      "24 months rate / percentage",
      "Downpayment requirement",
      "Computation type",
      "Enable custom term",
    ],
    priority: true,
  },
  {
    title: "Price Tier Settings",
    description: "Configurable item price tier labels and staff usage rules.",
    items: [
      "Price 1 label",
      "Price 2 label",
      "Price 3 label",
      "Price 4 label",
      "Price 5 label",
      "Default price tier",
      "Allow staff to choose tier",
      "Allow price override",
    ],
  },
  {
    title: "Discount Rules",
    description: "Controls discount limits and approval requirements.",
    items: [
      "Allow discount",
      "Discount type allowed",
      "Maximum discount per role",
      "Require approval above limit",
      "Discount reason required",
    ],
  },
  {
    title: "Inventory Rules",
    description: "Stock, low stock, serial, and adjustment settings.",
    items: [
      "Default low stock threshold",
      "Use item minimum stock",
      "Allow negative stock",
      "Require serial by category",
      "Stock adjustment approval",
      "Stock request between branches",
      "Emergency stock request",
    ],
  },
  {
    title: "Warranty Rules",
    description: "Warranty workflow settings and claim requirements.",
    items: [
      "Default warranty duration",
      "Warranty statuses",
      "Require original sale reference",
      "Require serial number",
      "Supplier warranty tracking",
      "Admin-only warranty without sale",
    ],
  },
  {
    title: "Service Rules",
    description: "Service job workflow and payment behavior.",
    items: [
      "Service categories",
      "Default service status",
      "Require technician assignment",
      "Allow service payment from POS",
      "Allow partial service payment",
      "Service completion approval",
    ],
  },
  {
    title: "Cash Box Rules",
    description: "Cash collection, non-cash separation, and handover rules.",
    items: [
      "Centralized cash box",
      "Assigned cash custodian",
      "Cash in categories",
      "Cash out categories",
      "Require handover confirmation",
      "Daily collection cut-off time",
      "Separate cash, GCash, bank, card, and cheque",
    ],
  },
  {
    title: "Incentive Rules",
    description: "Employee and item-based incentive configuration.",
    items: [
      "Enable incentives",
      "Default incentive percentage",
      "Item-based incentive percentage",
      "Employee-based incentive rule",
      "Who can view incentives",
      "When incentive counts",
    ],
  },
  {
    title: "Document Numbering",
    description: "Document prefixes and numbering format.",
    items: [
      "Receipt prefix",
      "Quotation prefix",
      "Warranty claim prefix",
      "Service job prefix",
      "Stock transfer prefix",
      "Purchase order prefix",
      "Purchase receiving prefix",
      "Cash transaction prefix",
    ],
  },
  {
    title: "System Preferences",
    description: "General app behavior and safe caching defaults.",
    items: [
      "Theme",
      "Default rows per page",
      "Currency symbol",
      "Date format",
      "Timezone",
      "Cache duration",
      "Auto-save draft interval",
      "Draft expiry days",
    ],
  },
]
